version: '3.8'

services:
  dashboard:
    build: ./dashboard
    container_name: devfarm-dashboard
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - devfarm-data:/data
      - /opt:/opt
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - GITHUB_USERNAME=${GITHUB_USERNAME:-bustinjailey}
      - GITHUB_EMAIL=${GITHUB_EMAIL:-bustinjailey@users.noreply.github.com}
      - DEBUG=false
      - HOST_REPO_PATH=/opt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - devfarm

networks:
  devfarm:
    name: devfarm
    driver: bridge

volumes:
  devfarm-data:
    name: devfarm-data
