version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: devfarm-proxy
    ports:
      - "5000:80"
    volumes:
      - ./proxy/nginx.conf.template:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/proxy-health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - devfarm
    depends_on:
      - dashboard

  dashboard:
    build: ./dashboard
    container_name: devfarm-dashboard
    expose:
      - "5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - devfarm-data:/data
      - /opt/dev-farm:/opt/dev-farm
    environment:
      - DEBUG=false
      - HOST_REPO_PATH=/opt/dev-farm
      # EXTERNAL_URL: Set this to your public URL for correct link generation
      # For local development: http://localhost:5000
      # For production: https://farm.bustinjailey.org (or your domain)
      - EXTERNAL_URL=https://farm.bustinjailey.org
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - devfarm
    depends_on:
      - updater
  
  # Terminal image builder - builds the image but doesn't run a container
  # This ensures the terminal image exists before trying to use it
  terminal-builder:
    build:
      context: ./docker
      dockerfile: Dockerfile.terminal
    image: dev-farm/terminal:latest
    container_name: devfarm-terminal-builder
    profiles:
      - build-only
    command: "true"
  
  updater:
    image: docker:27-cli
    container_name: devfarm-updater
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/dev-farm:/opt/dev-farm
    restart: unless-stopped
    command: tail -f /dev/null
    networks:
      - devfarm

networks:
  devfarm:
    name: devfarm
    driver: bridge

volumes:
  devfarm-data:
    name: devfarm-data
